### ISSUE TITLE
MiMa failing 

### ISSUE THREAD

**Issue by armanbilge** [typelevel/fs2-grpc#478]
Due to https://github.com/typelevel/fs2-grpc/pull/477, sorry! I'm a little confused how it passed CI but not on main.

```
[error] (codegen / mimaPreviousClassfiles) sbt.librarymanagement.ResolveException: Error downloading org.typelevel:fs2-grpc-codegen_2.12:2.4.3
```

**Comment by ahjohannessen** [comment]
Can it be related to that change of Scala order?

**Comment by armanbilge** [comment]
Oh, I see, you just tagged 2.4.3. Yikes, I thought these race conditions are fixed.

**Comment by ahjohannessen** [comment]
How do we go about fixing that?

**Comment by armanbilge** [comment]
There are two failures here:
1. On the CI job started for the push, which is https://github.com/typelevel/sbt-typelevel/issues/75. Annoying but fixable.
2. On the CI job started for the tag, which I don't totally understand yet why it failed. Looking into it now.

The workaround is to wait for CI to on main to finish before creating a tag/release.

**Comment by armanbilge** [comment]
Ok, I understood (2) and logged it in https://github.com/typelevel/sbt-typelevel/issues/76.

I think I know how to fix both. Sorry for the trouble 😬

**Comment by ahjohannessen** [comment]
No problem @armanbilge - You are doing good work!

**Comment by ahjohannessen** [comment]
I deleted the 2.4.3 tag and release - as that never hit sonatype

**Comment by armanbilge** [comment]
Thanks :) I have a fix incoming :)

**Comment by ahjohannessen** [comment]
@armanbilge Now CI is green, is it safe to tag a version now?

**Comment by armanbilge** [comment]
Unfortunately no, it is still affected by https://github.com/typelevel/sbt-typelevel/issues/76 I believe. I'm about to push a fix, we'll have you publishing shortly :)

**Comment by ahjohannessen** [comment]
ok 👍
