### ISSUE TITLE
Any example of using scalapb validators with fs2-grpc?

### ISSUE THREAD

**Issue by berserk-fan** [typelevel/fs2-grpc#489]

**Comment by ahjohannessen** [comment]
Not that I know of, however valididation is on message types and that is ScalaPB territory and I suppose if you follow the docs for validation on the ScalaPB website you should be able to use that together with fs2-grpc as you would with scalapb-grpc

**Comment by mamat14** [comment]
Thanks for the quick response.

Fixed the issue(Tried to insert into file that doesn't exist.)

The problem was that I didn't pass the same options to scalapb.validate.get and fs2-grpc. I made an ad hoc solution. There is working code.

```
//remeber to pass the same options to fs2-grpc and scalapb.validate
enablePlugins(Fs2Grpc)
scalapbCodeGeneratorOptions += CodeGeneratorOption.Fs2Grpc
scalapbCodeGeneratorOptions += CodeGeneratorOption.FlatPackage

Compile / PB.targets := scalapbCodeGenerators.value
  .map(_.copy(outputPath = (Compile / sourceManaged).value / "scala")) //intellij specific
  .:+(scalapb.validate.gen(GeneratorOption.FlatPackage) -> (Compile / sourceManaged).value / "scala": protocbridge.Target)

```
