### ISSUE TITLE
Metadata with response

### ISSUE THREAD

**Issue by a-khakimov** [typelevel/fs2-grpc#528]
I correctly understand that there is no possibility to send metadata with response?

**Comment by ahjohannessen** [comment]
A PR would be nice to see, as long as it is non-breaking and opt-in

**Comment by choonkending** [comment]
@a-khakimov By any chance did you have a working branch or idea of how to add this? 🙏 My team is keen on getting this functionality as well.

**Comment by TalkingFoxMid** [comment]
add in https://github.com/typelevel/fs2-grpc/pull/713

**Comment by ahjohannessen** [comment]
Fixed in https://github.com/typelevel/fs2-grpc/pull/713
