### ISSUE TITLE
Grpc status exceptions are rethrown

### ISSUE THREAD

**Issue by ValdemarGr** [typelevel/fs2-grpc#572]
In our app we are experiencing exceptions in our (stderr) logs even though they are grpc status exceptions.

It seems that status exceptions are logged by the cats-effect runtime when thrown, since `guarentee` rethrows.

https://github.com/typelevel/fs2-grpc/blob/f65bb386255b916a6087397614dd7fce0c37e806/runtime/src/main/scala/fs2/grpc/server/internal/Fs2ServerCall.scala#L86-L95

I'm not sure what the best course of action is for non-status exceptions, but for status exceptions I believe it doesn't make much sense to rethrow them.

We are using the following fix locally:
```scala
  private def run[F[_]](completed: F[Unit], dispatcher: Dispatcher[F])(implicit F: Sync[F]): SyncIO[Cancel] = {
    SyncIO {
      val cancel = dispatcher.unsafeRunCancelable(
        F.recover {
          F.guaranteeCase(completed) {
            case Outcome.Succeeded(_) => close(Status.OK, new Metadata()).to[F]
            case Outcome.Errored(e) => handleError(e).to[F]
            case Outcome.Canceled() => close(Status.CANCELLED, new Metadata()).to[F]
          }
        } { case _: StatusException | _: StatusRuntimeException =>
          ()
        }
      )
      SyncIO(cancel()).void
    }
  }
```

If possible, it would be nice to either make the handler for non-status exceptions configurable or not throw them at all, since the default exception reporter does not respect logging configuration.

**Comment by ahjohannessen** [comment]
So, everything that comes out of `Outcome.Errored(e)` is transformed into a `StatusRuntimeException` or `StatusException` via `handleError`. I am not sure what you mean by non-status exceptions, as everything is turned into one when closing the call in the case of an error.

I agree that rethrowing them seems pointless.

**Comment by ValdemarGr** [comment]
What I am addressing is only rethrowing.

Nevertheless it seems that you agree in rethrowing being pointless 🙂

I'll open a PR

**Comment by ahjohannessen** [comment]
👍
