### ISSUE TITLE
Use io.grpc.Grpc factory methods instead of NettyServerBuilder/NettyChannelBuilder in docs

### ISSUE THREAD

**Issue by igor-vovk** [typelevel/fs2-grpc#734]
Hi!
I want to propose changing the docs from importing `io.grpc.netty.shaded.io.grpc.netty.*` package and using `NettyServerBuilder` and `NettyChannelBuilder` factory classes that feel like implementation classes, to using instead `Grpc.newServerBuilderForPort` and `Grpc.newChannelBuilderForAddress` factory methods from `io.grpc` package in the documentation. 

Will be happy to open a PR.

**Comment by igor-vovk** [comment]
I've tried making changes in https://github.com/typelevel/fs2-grpc/pull/735 but it didn't work – factory methods of the `io.grpc.Grpc` object return `ManagedChannelBuilder<?>` and `ServerBuilder<?>` types, which break implicit conversions, producing an error:
```
Type argument ?1.CAP does not conform to upper bound io.grpc.ManagedChannelBuilder[?1.CAP] in inferred type io.grpc.ManagedChannelBuilder[?1.CAP]

where:    ?1 is an unknown value of type scala.runtime.TypeBox[Nothing, io.grpc.ManagedChannelBuilder[Object]]

      .newChannelBuilderForAddress("127.0.0.1", 0, InsecureChannelCredentials.create())
```

Wrapping values in `ManagedChannelBuilderOps()` and `ServerBuilderOps()` by hand works. I spent quite some time with it but couldn't make implicits work. So this may require changes in the API of the library, if you think it makes sense to do this switch.

**Comment by igor-vovk** [comment]
What I found, is that calling any method on `ManagedChannelBuilder` or `ManagedServerBuilder` switches type to be again an `A<? extends A>>`, which makes implicits work.

**Comment by ahjohannessen** [comment]
If you manage to introduce something that is more general in your PR that does not break existing code, I can review it.

**Comment by igor-vovk** [comment]
Going to close this one then. Gave it another try but couldn't make it work.
